### ISSUE TITLE
Browserify doesn't run on Windows

### ISSUE THREAD

**Issue by leerichard42** [AnalyticalGraphicsInc/gltf-pipeline#12]
```
Richard@Richard-PC /cygdrive/c/Users/Richard/src/gltf-pipeline
$ npm run build

> gltf-pipeline@0.0.0 build C:\Users\Richard\src\gltf-pipeline
> browserify index.js --standalone gltfPipeline -o build/gltf-pipeline.js

Error: Cannot find module './process' from 'C:\Users\Richard\src\gltf-pipeline\node_modules\cesium\node_modules\requirejs\bin'
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\Richard\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Richard\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! gltf-pipeline@0.0.0 build: `browserify index.js --standalone gltfPipeline -o build/gltf-pipeline.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gltf-pipeline@0.0.0 build script 'browserify index.js --standalone gltfPipeline -o build/gltf-pipeline.js'.
npm ERR! This is most likely a problem with the gltf-pipeline package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify index.js --standalone gltfPipeline -o build/gltf-pipeline.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gltf-pipeline
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Richard\src\gltf-pipeline\npm-debug.log
```

**Comment by pjcozzi** [comment]
Also fails on Mac now.

**Comment by lasalvavida** [comment]
@JoshuaStorm 

I'm going to write down here a little synopsis of the problem if you want to keep looking at it.

Some of our dependencies use dynamic requiring:
`require('foobar')`
as opposed to
`var foo = 'foo';
var bar = 'bar';
require(foo+bar);`

which is a valid way to use require, but not one that browserify supports.

Webpack does a lot of the same things that browserify does, and does allow dynamic requiring, but if I recall has some issues converting some of the node-specific modules.

**Comment by pjcozzi** [comment]
@lasalvavida thanks for the notes.

@JoshuaStorm no need to investigate this now.

**Comment by lilleyse** [comment]
For the meantime we're removing support for Browserify, so I'm closing this.
