### ISSUE TITLE
GLTF from .dae file

### ISSUE THREAD

**Issue by shiva416** [AnalyticalGraphicsInc/gltf-pipeline#199]
Hi,

I need to convert .dae to .glb files which are more than 10MB files. Inorder to do the conversion I was following below steps,
Step 1: Use Collada2GLTF utility to convert .dae to .gltf files. This works fine.
Step 2: Use GLTF-Pipeline utility thru Node.js to converted exported .gltf files to .glb.

When I perform Step 2 with attached files I end up having below exception.
Appreciate any help.

Command:
node ./bin/gltf-pipeline.js -i ./input/WheelsandDriveUnit.gltf -o WheelsandDriveUnit.glb

Error:
Unhandled rejection TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1026:11)
    at Buffer.writeUInt16LE (buffer.js:1084:5)
    at writeBufferComponent (C:\gltf-pipeline-master\gltf-pipeline-master\lib\wr
iteBufferComponent.js:24:27)
    at createAccessor (C:\gltf-pipeline-master\gltf-pipeline-master\lib\createAc
cessor.js:49:13)
    at createPrimitive (C:\gltf-pipeline-master\gltf-pipeline-master\lib\combine
Primitives.js:247:29)
    at combinePrimitivesInGroup (C:\gltf-pipeline-master\gltf-pipeline-master\li
b\combinePrimitives.js:222:33)
    at combinePrimitives (C:\gltf-pipeline-master\gltf-pipeline-master\lib\combi
nePrimitives.js:41:42)
    at Function.Pipeline.processJSONWithExtras (C:\gltf-pipeline-master\gltf-pip
eline-master\lib\Pipeline.js:97:5)
    at C:\gltf-pipeline-master\gltf-pipeline-master\lib\Pipeline.js:207:29
    at tryCatcher (C:\gltf-pipeline-master\gltf-pipeline-master\node_modules\blu
ebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\gltf-pipeline-master\gltf-pipeline-
master\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\gltf-pipeline-master\gltf-pipeline-master\node
_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\gltf-pipeline-master\gltf-pipeline-master\nod
e_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\gltf-pipeline-master\gltf-pipeline-master\nod
e_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\gltf-pipeline-master\gltf-pipeline-master\node_modul
es\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\gltf-pipeline-master\gltf-pipeline-master\no
de_modules\bluebird\js\release\promise.js:431:57)

[WheelsandDriveUnit.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/662238/WheelsandDriveUnit.zip)

**Comment by lasalvavida** [comment]
This model has a great deal of geometry data and when gltf-pipeline optimizes the primitives together, we end up with indices `> 65535`. Currently uint32 indices support is in glTF 1.1 but we don't add it by default since most engines don't support it yet.

I've just opened #200 for disabling the optimization stages. Feel free to use that now, wait for it to get merged, or alternatively, you can comment out the `combinePrimitives` function in `processJSONWithExtras` in `lib/Pipeline.js`.

**Comment by shiva416** [comment]
Thanks Guys..I took the latest build after the merge and it did solve the issue...

**Comment by shiva416** [comment]
I have re-opened this as per comments in #200.
