### ISSUE TITLE
Ambient occlusion broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/gltf-pipeline#259]
Whenever I try and enable AO, the pipeline crashes with an unfriendly call stack:

```
Unhandled rejection Error
    at new DeveloperError (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\cesium\Source\Core\DeveloperError.js:44:19)
    at Function.Cartesian3.normalize (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\cesium\Source\Core\Cartesian3.js:422:19)
    at raytraceAtTriangleCenters (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\bakeAmbientOcclusion.js:1160:20)
    at forEachPrimitiveInNode (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\NodeHelpers.js:222:13)
    at Function.NodeHelpers.depthFirstTraversal (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\NodeHelpers.js:126:17)
    at Function.NodeHelpers.forEachPrimitiveInScene (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\NodeHelpers.js:201:25)
    at bakeAmbientOcclusion (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\bakeAmbientOcclusion.js:92:21)
    at Function.Pipeline.processJSONWithExtras (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\Pipeline.js:138:9)
    at C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\Pipeline.js:258:29
    at tryCatcher (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:432:57)
```

Digging into it, it appears `backAmbientOcclusion` attempts to normalize a zero vector, leading to the crash, however we aren't properly handling rejected promises so the error doesn't make it up to the user in a meaningful way.  I'll write up a separate issue to review all promise usage to make sure we provide meaningful errors on the command line.

I was testing with several models, but this fresh convert of the Cesium Man is a good test case (rename the extension): [Cesium_Man.glb.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/905688/Cesium_Man.glb.txt)

The command line I used was:
```
./bin/gltf-pipeline.js -i /C/Data/Cesium_Man.glb -o /C/Data/Cesium_Man2.glb --ao.enable
```

**Comment by mramato** [comment]
Hold off on this, it may be a false alarm.  Looks like there may actually be a bug in the Collada to gltf converter.

**Comment by mramato** [comment]
Yep, it's a bug in our model optimization code, not AO (though AO still needs improved error handling so I'll write up a separate issue for that).

Sorry for the noise
