### ISSUE TITLE
Crash when converting from gltf to glb

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/gltf-pipeline#268]
The following command crashes with a developer error:

`gltf-pipeline -i dragonAO.gltf -o dragonAO.glb -b`

I also tried without the binary, same reuslt

`gltf-pipeline -i dragonAO.gltf -o dragonAO2.gltf`

Here's the file: (remove the extra extension) [dragonAO.zip.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/938069/dragonAO.zip.txt)

__Callstack__
```
    at new DeveloperError (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\cesium\Source\Core\DeveloperError.js:44:19)
    at Function.Cartesian3.normalize (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\cesium\Source\Core\Cartesian3.js:422:19)
    at Object.transformPrimitives (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\gltf-pipeline\lib\PrimitiveHelpers.js:155:28)
    at mergeChildrenIntoNode (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\gltf-pipeline\lib\combineNodes.js:112:50)
    at Object.<anonymous> (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\gltf-pipeline\lib\combineNodes.js:57:13)
    at JSONPath.<anonymous> (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\jsonpath\lib\index.js:44:31)
    at Array.forEach (native)
    at JSONPath.apply (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\jsonpath\lib\index.js:41:9)
    at combineNodes (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\gltf-pipeline\lib\combineNodes.js:39:8)
    at Function.Pipeline.processJSONWithExtras (C:\Git\AnalyticalGraphicsInc\agi-cesium-cloud\node_modules\gltf-pipeline\lib\Pipeline.js:121:9)
```

CC @pjcozzi @lilleyse

**Comment by likangning93** [comment]
Heads up, some version of the dragon has (for reasons unknown...) NaN normals, hence the crash outside of anything that seems like it should involve computing normals. 
I should fix that and redistribute the model, but I think we do still have a `sanitizeNormals` stage planned.

**Comment by lilleyse** [comment]
This no longer crashes and the output model loads in Cesium. Likely fixed by removing the optimization stages.
