### ISSUE TITLE
Model fails to round trip

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/gltf-pipeline#277]
Here is a quantized version of the BrainStem sample model: [BrainStem-q.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/973843/BrainStem-q.zip)

Running `gltf-pipeline -i /BrainStem-q.gltf -o out.gltf` results in a crash with the below call stack.  It looks like we're passing an invalid offset when constructing the `Uint8Array` from the buffer.

```
Unhandled rejection RangeError: Invalid typed array length
    at new Uint8Array (native)
    at packGltfBuffer (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\uninterleaveAndPackBuffers.js:64:29)
    at uninterleaveAndPackBuffers (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\uninterleaveAndPackBuffers.js:32:13)
    at cesiumGeometryToGltfPrimitive (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\cesiumGeometryToGltfPrimitive.js:100:5)
    at optimizeForVertexCache (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\optimizeForVertexCache.js:94:21)
    at Function.Pipeline.processJSONWithExtras (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\Pipeline.js:130:9)
    at C:\Git\AnalyticalGraphicsInc\gltf-pipeline\lib\Pipeline.js:261:29
    at tryCatcher (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Git\AnalyticalGraphicsInc\gltf-pipeline\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
```

**Comment by mramato** [comment]
Fixed in #279
