### ISSUE TITLE
gltf-pipeline 2.0 creating empty models from gltf2 files

### ISSUE THREAD

**Issue by DJviolin** [AnalyticalGraphicsInc/gltf-pipeline#337]
I'm running on Windows 10 and I installed `gltf-pipeline` locally in my project. I running the command with this line from `package.json`:

```json
"gltf-pipeline": "node ./node_modules/gltf-pipeline/bin/gltf-pipeline.js -i ./ar/models/photoscan/gltf/model.gltf -o ./ar/models/photoscan/glb/model.gltf --stats",
```

Which is generating the following gltf file:

```json
{"accessors":{},"asset":{"generator":"Khronos Blender glTF 2.0 exporter","version":"2.0","premultipliedAlpha":false,"profile":{"api":"WebGL","version":"1.0.3"}},"bufferViews":{},"buffers":{},"images":{},"materials":{},"meshes":{},"nodes":{"rootNode":{"children":[],"meshes":[],"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}},"samplers":{},"scene":0,"scenes":[{"name":"Scene","nodes":["rootNode"]}],"textures":{},"animations":{},"cameras":{},"programs":{},"shaders":{},"skins":{},"techniques":{},"extensionsUsed":[]}
```

And this is my console output:

```sh
Statistics for ar\models\photoscan\gltf\model.gltf
------------------
Total size of all buffers: 81072 bytes
Images: 1
Draw calls: 1
Rendered primitives (e.g., triangles): 2000
Nodes: 1
Meshes: 1
Materials: 1
Animations: 0
External requests (not data uris): 2

Statistics for ar\models\photoscan\glb\model.gltf
------------------
Total size of all buffers: 0 bytes
Images: 0
Draw calls: 0
Rendered primitives (e.g., triangles): 0
Nodes: 1
Meshes: 0
Materials: 0
Animations: 0
External requests (not data uris): 0

optimize: 208.208ms
```

Thank You for your help!

**Comment by hpinkos** [comment]
Hi @DJviolin, are you using the [2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0)?  The work for glTF 2.0 is being worked on in that branch and hasn't been merged into master yet.

**Comment by DJviolin** [comment]
I'm using the following versions in my package:

```json
$ npm list --depth=0
magyarkert@1.0.0 D:\www\magyarkert
+-- babel-eslint@8.0.2
+-- eslint@4.11.0
+-- eslint-config-airbnb-base@12.1.0
+-- eslint-plugin-babel@4.1.2
+-- eslint-plugin-import@2.8.0
+-- gltf-pipeline@1.0.2
+-- obj2gltf@2.0.0
+-- wdio-firefox-profile-service@0.1.0
`-- webdriverio@4.9.9
```

**Comment by hpinkos** [comment]
@DJviolin `gltf-pipeline@1.0.2` doesn't have glTF 2.0 support.  You'll have to use the 2.0 branch to test things out until we have some time to clean that up and get it merged into master.  Thanks!

**Comment by DJviolin** [comment]
I installed gltf-pipeline from the 2.0 branch with the following command:

```sh
$ npm install -g git+https://git@github.com/AnalyticalGraphicsInc/gltf-pipeline.git#2.0
```

I'm getting this error message both locally and globally:

```
$ gltf-pipeline --help
C:\Users\User\AppData\Roaming\npm\node_modules\gltf-pipeline\node_modules\cesium\Source\ThirdParty\crunch.js:42
    var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&

Error: Cannot find module '../lib/Pipeline'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\gltf-pipeline\bin\gltf-pipeline.js:4:16)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

**Comment by lilleyse** [comment]
I should add that the `2.0` branch isn't stable right now. Progress is being tracked here https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/330.

For now I wouldn't recommend including it in a glTF 2.0 project, but we hope to get further with it soon.

**Comment by DJviolin** [comment]
Seems like that missing file is presented in the Cesium branch, maybe I should try that?

I only want to pack my .gltf, .bin, texture files into a .glb.

**Comment by lilleyse** [comment]
That branch may have some issues as well. Since you are doing a straight gltf to glb conversion, I would recommend checking out the glTF VS Code extension: https://github.com/AnalyticalGraphicsInc/gltf-vscode, which can convert gltf + external resources to a glb.

**Comment by DJviolin** [comment]
Thank You, I will check it out!
