### ISSUE TITLE
Expected path.protocol to start with file:

### ISSUE THREAD

**Issue by nsbingham** [AnalyticalGraphicsInc/gltf-pipeline#497]
I'm running node v10.16.3 on Mac Mojave 10.14.6. I get the error below when running the following through the command line:
`gltf-pipeline -i tmp/tmp.gltf -o optimized.glb`

Files are named appropriately and paths are correct. Is there another way I need to be formatting my paths for this project?

```
{ Error
    at new RuntimeError (/usr/local/lib/node_modules/gltf-pipeline/node_modules/cesium/Source/Core/RuntimeError.js:42:19)
    at fileURLToPath (/usr/local/lib/node_modules/gltf-pipeline/lib/FileUrl.js:38:15)
    at readFile (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:135:26)
    at readResource (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:110:12)
    at readImage (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:74:12)
    at /usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:54:39
    at Function.ForEach.object (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:46:27)
    at Function.ForEach.topLevel (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:65:20)
    at Function.ForEach.image (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:186:20)
    at /usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:53:21
    at tryCatcher (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:643:18)
  name: 'RuntimeError',
  message: 'Expected path.protocol to start with file:',
  stack:
   'Error\n    at new RuntimeError (/usr/local/lib/node_modules/gltf-pipeline/node_modules/cesium/Source/Core/RuntimeError.js:42:19)\n    at fileURLToPath (/usr/local/lib/node_modules/gltf-pipeline/lib/FileUrl.js:38:15)\n    at readFile (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:135:26)\n    at readResource (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:110:12)\n    at readImage (/usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:74:12)\n    at /usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:54:39\n    at Function.ForEach.object (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:46:27)\n    at Function.ForEach.topLevel (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:65:20)\n    at Function.ForEach.image (/usr/local/lib/node_modules/gltf-pipeline/lib/ForEach.js:186:20)\n    at /usr/local/lib/node_modules/gltf-pipeline/lib/readResources.js:53:21\n    at tryCatcher (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/usr/local/lib/node_modules/gltf-pipeline/node_modules/bluebird/js/release/promise.js:643:18)' }
```

**Comment by nsbingham** [comment]
Looks like some of my images are prefixed with blob:.
