### ISSUE TITLE
CLI throws ERR_REQUIRE_ESM error

### ISSUE THREAD

**Issue by luigimannoni** [AnalyticalGraphicsInc/gltf-pipeline#520]
Cant use the CLI at all after installing the package from npm with the global flag, this happens with all the last 4 versions of the package.

Tested with node LTS, 13.6 and 13.8. 
OS: Linux phobos 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Terminal output with stack trace:

```
$ gltf-pipeline 
internal/modules/cjs/loader.js:1167
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/gltf-pipeline/node_modules/cesium/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/gltf-pipeline/node_modules/cesium/index.js from /usr/lib/node_modules/gltf-pipeline/bin/gltf-pipeline.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/gltf-pipeline/node_modules/cesium/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/gltf-pipeline/bin/gltf-pipeline.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by lilleyse** [comment]
@luigimannoni - see https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/507, for the time being you'll need to use Node 12.
